config/routes.rb
Rails.application.routes.draw do
  get 'pages/my_bookings', to: "pages#my_bookings"
  get 'pages/my_places', to: "pages#my_places"
  devise_for :users

  root to: 'pages#home'
  resources :places do
      resources :bookings, only: [:new, :create]
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :date, presence: true
  # validates :name, presence: true
  #ajouté une validation scopé, une place peut etre reservé une seule fois
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  has_many_attached :photos
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id' #belongs to owner, association
  validates :name, presence: true
  validates :description, presence: true
  # validates :options, presence: true, inclusion: { in: ['Restauration', 'Electricité', 'Autorisations', 'Ménage', 'Fumeur', 'Wifi', 'Piscine', 'WC', 'Accessibilité', 'Matériel Audiovisuel', 'Meublé' ]}
  has_many :bookings
  validates :city, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['habitation', 'industriel', 'exterieur', 'culturel']}
  # mount_uploader :photo, PhotoUploader

  include PgSearch::Model
  pg_search_scope :search_places_all,
                  against: %i[city category price],
                  using: {
                    tsearch: { prefix: true }
                  }
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # before_action :authenticate_user! -> set up a controller with user authentication
  # after_sign_in_path_for and after_sign_out_path_for -> redirect after sign in
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  has_many :places
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @place = Place.find(params[:place_id])
    #get new.html.erb -> formulaire generant new instance de booking
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    # POST le formulaire est founris et alimente la base de donnée, params: uder_id, place_id, date
    @place = Place.find(params[:place_id])
    @booking = Booking.new(booking_params)
    @booking.place = @place
    @booking.user = current_user
    @booking.save!
    redirect_to root_path
  end

private
#hidden field pourn le simple form
  def booking_params
    params.require(:booking).permit(:date, :message, :name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def my_bookings
  # params.require(:booking).permit(:date, :place_id)
  end

private

  def my_places
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    # JS ecouter l'événement
    @query = params[:search]
   if params[:search].present?
    if params[:search][:city].present?
      @places = Place.where("city ILIKE ?", "%#{params[:search][:city]}%")
    elsif params[:search][:category].present?
      @places = Place.where("category ILIKE ?", "%#{params[:search][:category]}%")
    elsif params[:search][:price].present?
      @places = Place.where("price ILIKE ?", "%#{params[:search][:price]}%")
      end
      else
        @places = Place.all
      end
  end

  def new
    @place = Place.new
  end

  def show
  @place = Place.find(params[:id])
  @marker = Place.near(@place.address, 0.5, units: :km)

    @markers = @marker.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude
      }
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
  end

  def create
    @place = Place.new(place_params)
    @place.owner = current_user



    @place.options.reject!(&:blank?)
    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end

private

  def place_params
    params.require(:place).permit(:name, :category, :price, :address, :city, :description, options: [], photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="main-cont" style="max-width: 950px">
  <h3 style="color: var(--corail) !important;">RESERVER UN BIEN</h3>
  <br>
  <p><%= @place.name %></p>
  <div class="container-form">
    <%= simple_form_for([@place, @booking]) do |f| %>
    <div class="form-group">
      <%= f.input :date, placeholder: 'jour/mois/année', label:'Vos dates', as: :date%>
      <%= f.input :message, placeholder: 'Message', label:'Votre message' %>
      <%= f.submit "Réserver", class: "btn btn-flat btn-form-rent" %>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Mes annonces :</h1>
<br>

<div class="cards">
  <% @bookings.each do |booking| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(255, 255, 255, 0.3), rgba(0,0,0,0.3)), url(https://picsum.photos/seed/picsum/200/300)">
    <p> <%= place.name %> </p><br>
    <%= place.city %> <br>
    <%= link_to '+', place %>
  <% end %>
<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway|Roboto">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/base.min.css" /> -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"/>
  <script src="https://kit.fontawesome.com/197e3e829b.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>

<body>

  <%= render 'pages/navbar' %>

  <div class='container' style="margin-top: 2em;">
  <%= yield %>
  </div>

  <%= render 'pages/footer' %>

  <%= javascript_pack_tag 'application' %>

</body>
</html>

app/views/layouts/slideshow.html.erb
<head>
  <script src="https://kit.fontawesome.com/c3d2918722.js" crossorigin="anonymous"></script>
</head>

<body>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" id="carrousel1" src="https://cdn.pixabay.com/photo/2017/03/30/04/14/house-2187170_960_720.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <h3>toto</h3>
        <p>tututututu</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" id="carrousel2" src="https://cdn.pixabay.com/photo/2020/02/08/16/14/villa-4830490_960_720.jpg" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <h3>toto</h3>
        <p>tututututu</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" id="carrousel3" src="https://cdn.pixabay.com/photo/2020/02/08/16/14/house-4830491_960_720.jpg" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
        <h3>toto</h3>
        <p>tututututu</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="" aria-hidden="true"><i class="fas fa-chevron-left"></i></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="" aria-hidden="true"><i class="fas fa-chevron-right"></i></span>
    <span class="sr-only">Next</span>
  </a>
</div>


</body>

app/views/pages/SearchCard.html.erb
<div class="container-card">
 <%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
     <%= f.input :ville, placeholder: 'Ville', label:false %>
      <%= f.input :category, placeholder: 'Catégorie', label:false %>
       <%= f.input :pxmax, placeholder: 'Prix max', label:false %>
         <%= link_to "Rechercher", "#", class: "btn btn-flat" %>
  </div>
</div>
<% end %>

app/views/pages/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <p class="p-logo">RENT4CULTURE</p>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <a class="navbar-brand" href="https://airbnb-gunter-dev-strike.herokuapp.com/">
    <span id="main-title">Rent4Culture</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <li>
        <div class="search-container">
          <form class=":search" method="get" action="/places">
            <input type="text" placeholder="Rechercher par ville" name="search[city]" style="margin-left: auto; border-color: var(--corail) !important; border-radius: 5px 0 0 5px !important; outline: none !important;">
            <button type="submit" style="margin-left: -19px; background-color: var(--corail); border: 5px; border-radius: 50%; color: var(--bleu);"><i class="fa fa-search"></i></button>
          </form>


      </div>
    </li>
    <li class="nav-item dropdown">
      <span class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Propriétaire</span>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "Ajouter un bien", new_place_path, class: "dropdown-item"%>
        <%= link_to "Mes annonces", pages_my_places_path, class: "dropdown-item"%>
        <%= link_to "Mes réservations", pages_my_bookings_path, class: "dropdown-item"%>
      </div>
    </li>
    <li class="nav-item">
      <%= link_to "Les annonces", places_path, class: "nav-link"%>
    </li>
    <li class="nav-item">

      <% if user_signed_in? %>
      <%= link_to "Deconnexion",  destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
      <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
    <li>
      <!-- <img class="avatar" src="https://kitt.lewagon.com/placeholder/users/ssaunier" /> -->
    </li>
  </ul>
</div>
</div>

app/views/pages/cardtextscroll.html.erb
<div class="container-scroll">
  <h1 class="h1-text-scroll">RENT4CULTURE</h1>
<div class="card-text-scroll">


  <p>Far from the truth, the apart gender reveals itself as a powered house to
    those who look. A susan is a taking postbox. However, a hoven share's jury
    comes with it the thought that the hipper tenor is a community. A russet stone
    is a probation of the mind. Earths are weekly psychiatrists. A pin can hardly be
    considered a hunted ellipse without also being a pint. What we don't know for
    sure is whether or not bananas are plastics goals. A driver is a governor from
  the right perspective.</p>

  <p>A talk is a corvine network. The withdrawals could be said to resemble
    rasping certifications. Some posit the groggy bat to be less than panniered.
    Framed in a different way, the dock is a fahrenheit. Unfortunately, that is
    wrong; on the contrary, the literature would have us believe that a prostyle
    drop is not but a sailor. They were lost without the accrued element that
    composed their hyacinth. Those tires are nothing more than violets. A sidewalk
  can hardly be considered a spendthrift toast without also being a decade.</p>

  <p>This is not to discredit the idea that a great-grandmother of the
    instruction is assumed to be a languid blue. The first phylloid technician
    is, in its own way, a bail. Before floods, prepareds were only mini-skirts. A
    travelled week is a japanese of the mind. A shoemaker sees a motorboat as an
    unweaned spring. As far as we can estimate, a prison is a shrubby desert. The
    dietician of a magazine becomes an elder doctor. As far as we can estimate, the
  minute is a litter.</p>

  <p>Far from the truth, the apart gender reveals itself as a powered house to
    those who look. A susan is a taking postbox. However, a hoven share's jury
    comes with it the thought that the hipper tenor is a community. A russet stone
    is a probation of the mind. Earths are weekly psychiatrists. A pin can hardly be
    considered a hunted ellipse without also being a pint. What we don't know for
    sure is whether or not bananas are plastics goals. A driver is a governor from
  the right perspective.</p>

  <p>A talk is a corvine network. The withdrawals could be said to resemble
    rasping certifications. Some posit the groggy bat to be less than panniered.
    Framed in a different way, the dock is a fahrenheit. Unfortunately, that is
    wrong; on the contrary, the literature would have us believe that a prostyle
    drop is not but a sailor. They were lost without the accrued element that
    composed their hyacinth. Those tires are nothing more than violets. A sidewalk
  can hardly be considered a spendthrift toast without also being a decade.</p>

  <p>This is not to discredit the idea that a great-grandmother of the
    instruction is assumed to be a languid blue. The first phylloid technician
    is, in its own way, a bail. Before floods, prepareds were only mini-skirts. A
    travelled week is a japanese of the mind. A shoemaker sees a motorboat as an
    unweaned spring. As far as we can estimate, a prison is a shrubby desert. The
    dietician of a magazine becomes an elder doctor. As far as we can estimate, the
  minute is a litter.</p>

</div>
</div>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="row">

    <div class="col">
      <div class="container-card">
       <%= simple_form_for :search, url: places_path, method: :get do |f| %>
       <div class="search-form-control form-group">
         <%= f.input :city, placeholder: 'Ville', label:false %>
         <%= f.input :options, label: false, collection: ['habitation', 'exterieur', 'industriel', 'culturel'], input_html: { class: 'choices' }, include_blank: false  %>
         <%= f.input :price, placeholder: 'Prix max', label:false %>
         <%= f.button :submit, "Rechercher",class:'btn_log_in' %>
       </div>
     </div>
     <% end %>

   </div>

   <div class="col">
    <div class="container-scroll">
      <h1 class="h1-text-scroll">RENT4CULTURE</h1>
      <div class="card-text-scroll">


        <p class="p-text-scroll">Nous vous proposons des lieux insolites et originaux
          à louer pour vos événements pro et/ou vos tournages audiovisuels.
        </p>

        <p class="p-text-scroll">
          Séminaires, journées d’études, conférences presse, conventions,
          lancement de produits, cocktails, déjeuners et dîners, showrooms,
        fashion week, défilés, pop-up stores… </p>

        <p class="p-text-scroll">
          Lofts, lieux industriels, rooftops, hôtels particuliers, lieux
          éphémères, magasins, parkings, appartements de réceptions, galeries,
          musées, terrasses et jardins, lieux de prestige VIP, lieux confidentiels,
          lieux cachés et bien d’autres sont des exemples de types de lieux
        commercialisés par l’agence.</p>

        <p class="p-text-scroll">Nous vous proposons de louer une salle en location sèche, ou en formule
        clé en mains.</p>

        <p class="p-text-scroll">Tous les jours, nous nous efforçons de rechercher les perles rares,
          atypiques de par leur décoration, architecture, vue, affectation première…
          afin de vous les proposer et faire de votre événement une occasion unique
        et importante pour vos invités et votre société ou marque.</p>

        <p class="p-text-scroll"> Nous disposons depuis quelques années de nos propres espaces que nous
          commercialisons de façon exclusive. Vous pouvez les retrouvez dans la
        rubrique ci dessous « Nos lieux exclusifs ».</p>

      </div>
    </div>
  </div>
</div>

<div class="container-home">
  <div class="row row-carrousel">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" id="carrousel1" src="https://i.pinimg.com/originals/d1/18/c3/d118c3f8eee0b51b71fca7f52e7cb460.jpg" alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h3>Chateau de Menthon St Bernard</h3>
            <p>Interieur et exterieur de ce magnifique chateau près d'annecy</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" id="carrousel2" src="https://upload.wikimedia.org/wikipedia/commons/5/5c/Paris_Tour_Montparnasse_from_the_Arc_de_Triomphe_20100505.jpg" alt="Second slide">
          <div class="carousel-caption d-none d-md-block">
            <h3>Tour Montparnasse</h3>
            <p>ne faites pas attention au crétin chauve et à son pote qui lavent les vitres...</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" id="carrousel3" src="https://lonelyplanetimages.imgix.net/a/g/hi/t/85295461ad2f47599cc4f8cdf1e2b4d7-parque-del-buen-retiro.jpg" alt="Third slide">
          <div class="carousel-caption d-none d-md-block">
            <h3>Parque del retiro</h3>
            <p>Superbe parc au coeur de Madrid</p>
          </div>
        </div>
         <div class="carousel-item">
          <img class="d-block w-100" id="carrousel2" src="https://media.senscritique.com/media/000008256902/1200/Amityville_la_maison_du_diable.jpg" alt="Second slide">
          <div class="carousel-caption d-none d-md-block">
            <h3>Superbe maison américaine</h3>
            <p>On dit qu'il s'y passe encore des choses étranges</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="" aria-hidden="true"><i class="fas fa-chevron-left"></i></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="" aria-hidden="true"><i class="fas fa-chevron-right"></i></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
</div>

app/views/pages/my_bookings.html.erb
<h1>Mes réservations</h1>
<br>

<% if current_user.bookings %>
 <% current_user.bookings.each do |booking| %>
    <p style="font-size: 24px"><%= booking.place.name%></p>
    <p><%= booking.message%></p>
    <p style="font-family: 'Raleway'; color: var(--bleu); font-weight: 600;"><%= booking.date%></p>
    <hr>
    <br>
    <% end %>
<% end %>

<div id="my-bookings">
<br>
</div>

app/views/pages/my_places.html.erb
<h1>Mes annonces :</h1>
<br>
<% if current_user.bookings %>
<div class="cards">
  <% current_user.places.each do |place| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(224, 218, 218, 0.6), rgba(255, 253, 253, 0.3)), url(<%= place.photos.first.nil? ? 'https://cdn.pixabay.com/photo/2017/09/17/18/15/lost-places-2759275_1280.jpg' : cl_image_path(place.photos.first.key) %>)">
    <p> <%= place.name %> <br>
      <%= place.city %> <br>
      <%= link_to '+', place %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

<div id="mes-annonces">
<br>
</div>


<!-- # User doit etre connecté et avoir des annonces, si on a le temps on fera le "else"
avec un "Vous n'avez pas de biens sur ce site"
mais pour la demo on va tricher  -->

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/destroy.html.erb
<h1>Places#destroy</h1>
<p>Find me in app/views/places/destroy.html.erb</p>

app/views/places/edit.html.erb
<%=form_for @user, :html => { id: "edit_place", class: "place_edit"} do |f|%>
      <%= f.input :name, placeholder: 'Chateau de Chambord', label:'Donner un nom à votre lieu' %>
      <%= f.input :address, placeholder: '10 rue des mouettes', label:'Adresse' %>
      <%= f.input :city, placeholder: 'Annecy', label:'Ville' %>
      <%= f.input :description, placeholder: 'Décriver votre lieu et ses usages possibles', label:'Description' %>
      <%= f.input :options, label:'Options' %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <% content_tag :button, :type => :submit, class: 'btn btn-primary' do %>
       <%= link_to "Modifer", new_user_registration_path, class:'sign_up_link' %>
    Update User
  <% end %>
<%end%>

app/views/places/index.html.erb
<h1>Les annonces :</h1>
<br>
<% if @places.nil? %>
<p> No places yet, search again</p>
<% else %>

<div class="cards">
  <% @places.each do |place| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(224, 218, 218, 0.6), rgba(255, 253, 253, 0.3)), url(<%= place.photos.first.nil? ? 'https://cdn.pixabay.com/photo/2017/09/17/18/15/lost-places-2759275_1280.jpg' : cl_image_path(place.photos.first.key) %>)">
    <p> <%= place.name %> <br>
      <%= place.city %> <br>
      <%= link_to '+', place %>

    </div>
    <% end %>
  </div>
  <% end %>

app/views/places/new.html.erb
<div class="main-cont" style="max-width: 950px">
  <h3>AJOUTER UN BIEN</h3>
  <br>
 <div class="container-form">

   <%= simple_form_for(@place) do |f| %>  <!-- #doit pouvoir add un bien  -->
    <div class="form-group">
      <%= f.input :name, placeholder: 'Chateau de Chambord', label:'Donner un nom à votre lieu', class: "opacity-placeholder"%>
      <%= f.input :address, placeholder: '10 rue des mouettes', label:'Adresse' %>
      <%= f.input :city, placeholder: 'Annecy', label:'Ville' %>
      <%= f.input :category, label: 'Catégorie', collection: ['habitation', 'exterieur', 'industriel', 'culturel'], input_html: { class: 'choices' }, include_blank: false %>
      <%= f.input :description, placeholder: 'Décrivez votre lieu et ses usages possibles', label:'Description' %>
      <%= f.input :options, label: 'Options', collection: ['Restauration', 'Electricité', 'Autorisations', 'Ménage', 'Fumeur', 'Wifi', 'Piscine', 'WC', 'Accessibilité', 'Matériel Audiovisuel', 'Meublé'], input_html: { class: 'choices', multiple: true }, include_blank: false %>
      <%= f.input :price, placeholder: 'Indiquez votre prix à la journée', label:'Prix' %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <%= f.submit "Enregistrer", class: "btn btn-flat btn-form"  %>

      <!--<%= link_to "Ajouter", class: "btn btn-flat btn-form"  %> -->

    </div>
  </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="show-container">

  <div class="place-container-pics">


 <div class="row row-carrousel">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @place.photos.each_with_index do |photo, index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="#{index}" <%= 'class="active"' if index == 1 %>></li>
        <% end %>
      </ol>
      <div class="carousel-inner">
        <% @place.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= "active" if index == 1 %>">
            <img class="d-block w-100" id="carrousel#{index}" src="<%= "#{cl_image_path(photo.key)}" %>" alt="First slide">
          </div>
        <% end %>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="" aria-hidden="true"><i class="fas fa-chevron-left"></i></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="" aria-hidden="true"><i class="fas fa-chevron-right"></i></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>


  </div>

  <div class="place-container-infos">

    <div class="place-infos">
      <h1><%= @place.name %></h1>
      <p><b>Ville : <%= @place.city  %></b></p>
      <p><b>Catégorie : <%= @place.category  %></b></p>
      <p><b>Addresse :  <%= @place.address  %></b></p>
      <p><b>Description :  <%= @place.description  %></b></p>
      <h3><%= @place.price %>€/jour</h3>

      <div class="btnandprice">
        <%= link_to "Reserver", new_place_booking_path(@place), class: "btn-rent" %>

      </div>
    </div>

    <div class="place-options">
      <h2>Options :</h2>
      <% @place.options.each do |option| %>
        <ul>
        <li class="liopts"><i class="fas fa-cog"></i> <b><%=  option %></b></li>
        </ul>
      <% end %>
    </div>
   <!-- <%= link_to "Modifer", edit_place_path, class:'edit_place-link' %>< -->

  </div>

  <div class="map-container" style="margin-bottom: 2em;">

 </div>
    <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>

app/views/places/update.html.erb
<h1>Places#update</h1>
<p>Find me in app/views/places/update.html.erb</p>